---

lightblue_config_dir: "/opt/wildfly/modules/com/redhat/lightblue/main"
lightblue_wildfly_user: "wildfly"
lightblue_wildfly_group: "wildfly"

lightblue_datasources:
  - metadata
  - futurxlabs_futurx
  - myorg_futurx
  - demo_futurx
  - futurxlabs_steerhigh
  - futurxlabs_serenaway
  - transform_serenaway
  - homeland_serenaway
  - letsbridgeit_serenaway
  - demo_serenaway
  - cgimelb_serenaway
  - cgisydney_serenaway
  - bmcbank_serenaway
  - mccia_serenaway
  - suprabha_futurx
  - srkexports_serenaway
  - bvp_serenaway
  - app_howzthat
  - app_commonviu
  - app_steerhigh
  - futurx_steerhigh
  - app_hirest
  - demo_steerhigh
  - sci-key_futurxlabs
  - futurxlabs_scikey
  - futurx_futurx
  - futurx_serenaway
  - public_scikey
  - enrich_serenaway
  - scikey_hirest
  - hire_scikey
  - career_srk

lightblue_dbservers:
  - host: 10.0.3.5
    port: 27017
